import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const generateAnalyticsPDF = async (userData, analyticsData, outputPath) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });

      // Ensure output directory exists
      const outputDir = path.dirname(outputPath);
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }

      const stream = fs.createWriteStream(outputPath);
      doc.pipe(stream);

      // Header
      doc.fontSize(24).text('CineScope Analytics Report', { align: 'center' });
      doc.moveDown();
      doc.fontSize(14).text(`Generated for: ${userData.fullName}`, { align: 'center' });
      doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'center' });
      doc.moveDown(2);

      // Stats Section
      doc.fontSize(18).text('Viewing Statistics', { underline: true });
      doc.moveDown();
      doc.fontSize(12);
      doc.text(`Total Movies Watched: ${analyticsData.moviesWatched}`);
      doc.text(`Total Watch Time: ${analyticsData.totalWatchTime}h`);
      doc.text(`Average Rating: ${analyticsData.averageRating.toFixed(1)}`);
      doc.text(`Reviews Written: ${analyticsData.reviewsWritten}`);
      doc.moveDown(2);

      // Genre Distribution
      if (analyticsData.genreDistribution && analyticsData.genreDistribution.length > 0) {
        doc.fontSize(18).text('Genre Distribution', { underline: true });
        doc.moveDown();
        doc.fontSize(12);
        analyticsData.genreDistribution.forEach((genre) => {
          doc.text(`${genre.name}: ${genre.percentage}%`);
        });
        doc.moveDown(2);
      }

      // Watch Time Chart Data
      if (analyticsData.watchTimeData && analyticsData.watchTimeData.length > 0) {
        doc.fontSize(18).text('Weekly Watch Time', { underline: true });
        doc.moveDown();
        doc.fontSize(12);
        analyticsData.watchTimeData.forEach((day) => {
          doc.text(`${day.day}: ${day.hours}h`);
        });
        doc.moveDown(2);
      }

      // Footer
      doc.fontSize(10)
        .text('Generated by CineScope AI', 50, doc.page.height - 50, {
          align: 'center',
        });

      doc.end();

      stream.on('finish', () => {
        resolve(outputPath);
      });

      stream.on('error', (err) => {
        reject(err);
      });
    } catch (error) {
      reject(error);
    }
  });
};

